### ISSUE TITLE
Unable to connect to PgSQL server error

### ISSUE THREAD

**Issue by wgyt** [scratchdit/scratchdit#38] opened 2021-04-24 00:00 UTC
**Describe the bug**
MyBB has an error connecting to the PgSQL server
**To Reproduce**

1. Go to 'https://scratchdit.herokuapp.com/'
2. See error

**Expected behavior**
No error
**Screenshots**
![image](https://user-images.githubusercontent.com/68466727/115940057-35266a80-a46e-11eb-85fd-d85a09ad331c.png)

**Desktop (please complete the following information):**

- OS: Chrome OS
- Browser: Chrome
- Version: 88.0.4324.208 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: iPhone 6s
- OS: iOS 14.4.2
- Browser: Chrome
- Version: 87.0.4280.163

**Additional context**
none

**Comment by RedGuy12** [comment] 2021-04-24 12:33
Duplicate of #35

But I honestly don't care anymore xD

**Closed by RedGuy12** 2021-04-24 12:33 UTC
Labels: status: needs triage, type: bug
